### ISSUE TITLE
Oraxen API Update

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCColor#1]
HMCColor does not currently load with Oraxen installed due to the API overhaul:

```
[15:45:49] [Server thread/ERROR]: Error occurred while enabling HMCColor v${version} (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "io.th0rgal.oraxen.items.OraxenItems.map" is null
	at io.th0rgal.oraxen.items.OraxenItems.entryStream(OraxenItems.java:151) ~[oraxen-1.147.1.jar:?]
	at io.th0rgal.oraxen.items.OraxenItems.exists(OraxenItems.java:57) ~[oraxen-1.147.1.jar:?]
	at com.hibiscusmc.hmccolor.HelpersKt.getDyeColorList(Helpers.kt:186) ~[HMCColor.jar:?]
	at com.hibiscusmc.hmccolor.HMCColor.onEnable(HMCColor.kt:16) ~[HMCColor.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1128) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by lucian929** [comment]
Fixed #2
