### ISSUE TITLE
0.8.1 Not Starting/Loading

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCColor#24]
[22:10:55 INFO]: [HMCColor] Loading server plugin HMCColor v0.8.1
[22:10:55 INFO]: [HMCColor] Enabling HMCColor v0.8.1
[22:10:55 ERROR]: Error occurred while enabling HMCColor v0.8.1 (Is it up to date?)
com.charleskorn.kaml.MissingRequiredPropertyException: Property 'item' is required but it is missing.
        at com.charleskorn.kaml.YamlInput.throwIfMissingRequiredPropertyException(YamlInput.kt:115) ~[HMCColor-0.8.1.jar:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:106) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColorConfig$$serializer.deserialize(HMCColorConfig.kt:8) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColorConfig$$serializer.deserialize(HMCColorConfig.kt:8) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[HMCColor-0.8.1.jar:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[HMCColor-0.8.1.jar:?]
        at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:54) ~[HMCColor-0.8.1.jar:?]
        at com.charleskorn.kaml.Yaml.decodeFromStream(Yaml.kt:47) ~[HMCColor-0.8.1.jar:?]
        at com.charleskorn.kaml.Yaml.decodeFromStream$default(Yaml.kt:46) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.idofront.config.IdofrontConfig.decode(IdofrontConfig.kt:55) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.idofront.config.IdofrontConfig.loadData(IdofrontConfig.kt:73) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.idofront.config.IdofrontConfig.<init>(IdofrontConfig.kt:51) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.idofront.config.IdofrontConfigBuilder.build(IdofrontConfigBuilder.kt:75) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColor$createColorContext$colorContext$1.<init>(HMCColor.kt:47) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColor.createColorContext(HMCColor.kt:34) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColor.onEnable(HMCColor.kt:16) ~[HMCColor-0.8.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:411) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1021) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1451) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2058]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.MissingFieldException: Field 'item' is required for type with serial name 'com.hibiscusmc.hmccolor.HMCColorConfig.Buttons', but it was missing
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColorConfig$Buttons.<init>(HMCColorConfig.kt:19) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColorConfig$Buttons$$serializer.deserialize(HMCColorConfig.kt:19) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.HMCColorConfig$Buttons$$serializer.deserialize(HMCColorConfig.kt:19) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[HMCColor-0.8.1.jar:?]
        at com.hibiscusmc.hmccolor.shaded.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[HMCColor-0.8.1.jar:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[HMCColor-0.8.1.jar:?]
        ... 48 more
[22:10:55 INFO]: [HMCColor] Disabling HMCColor v0.8.1
>

**Comment by Boy0000** [comment]
Your version is outdated and config malformed. Update to latest and as the 0.8.1 release said regenerate ur config
